spring:
  datasource:
    name: test #数据库名
    url: jdbc:mysql://localhost:3306/mydb #url
    username: root  #用户名
    password: lzy072  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.back_dev.Entity